---
- name: Deploy Nginx Container with podman
  hosts: ubuntuserver_vm
  become: true
  vars:
    acr_name: "jmppcp2acr.azure.io"
    acr_username: "jmppcp2acr"
    nginx_image: "nginx/nginx:casopractico2"
  tasks:
    - name: Ensure Podman is installed
      ansible.builtin.apt:
        name: podman
        update_cache: yes
        state: present

    - name: Login to ACR
      containers.podman.podman_login:
        registry: "{{ acr_name }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"

    - name: Pull Nginx image from ACR
      containers.podman.podman_image:
        name: "{{ acr_name }}/{{ nginx_image }}"

    - name: Run Nginx container
      containers.podman.podman_container:
        name: nginx
        image: "{{ acr_name }}/{{ nginx_image }}"
        state: started
        ports:
          - "80:80"